### ISSUE TITLE
compress data and write to ewf in 2 hosts

### ISSUE THREAD

**Issue by sspring** [libyal/libewf#121]
I know data can be compressed and written to libewf_data_chunk_t using libewf_data_chunk_write_buffer function.In my case there is a littile difference.I have two hosts,the high performance one is for compressing data and the other is for writing data to ewf. 
I'm thinking up the following two solutions:  
1. generate libewf_data_chunk_t  with compressed data,so that I can use `libewf_data_chunk_write_buffer`
2. share one libewf_data_chunk_t object  between two hosts.   
Can I get any suggestion?

**Comment by joachimmetz** [comment]
Know that the proposed approach adds additional network IO and latency to the process. Unclear to me from your description why you would want to do that.

> share one libewf_data_chunk_t object between two hosts.

This is not supported by libewf. Since a libewf_chunk is simple struct with binary data, you could either send the compressed data to the other host or use some serialization method.

**Comment by joachimmetz** [comment]
No additional explanation/feedback from original reporter, closing issue
