### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by vitlav** [libyal/libewf#127]
Please make a new release. With a tag, with a version and with a tarball.

**Comment by joachimmetz** [comment]
This repo contains the experimental version. If you want a release use: https://github.com/libyal/libewf-legacy/releases

**Comment by JustMyGithub** [comment]
Can you describe the difference of the repos, because I don't really understand. libewf-legacy has current releases that seem to just count up a version number that looks like a date from 6 years ago but have been posted just a few days/weeks ago. This and the changelogs make me think that those are maintanance releases for a "feature-complete" 6 year old software.

I had issues with a splitted .e01 (not .ex01 afaik) that occured with the 2014XXXX but not with a self-compiled experimental version, so there seem to be real-world-issues with the "stable" version which is not very surprising if basically it is 6 year old code.

I think a new release would help to spread more current versions, as maintainers probably do not want to pack "arbitrary nightly version", because you as "not the developer" never know in which condition the code in an experimental branch/repo is at the point of download.

Or do you consider the state of the repo too "unclean" or as not having enought useful updates during the last almost 3 years since the last release?

I noticed you were working a lot on test and rewrite/clean up but some of the commits sounds like they would be pretty useful.

No request for justification, of course - just curious. Thanks

**Comment by joachimmetz** [comment]
> libewf-legacy has current releases that seem to just count up a version number that looks like a date from 6 years ago but have been posted just a few days/weeks ago.

Correct this is just number to indicate a version. Issues in the legacy versions are still being addressed, just that no new functionality (like Ex01 support) will be added.

> I had issues with a splitted .e01 (not .ex01 afaik) that occured with the 2014XXXX but not with a self-compiled experimental version, so there seem to be real-world-issues with the "stable" version which is not very surprising if basically it is 6 year old code.

Please report such issues to https://github.com/libyal/libewf-legacy/issues, I cannot address issues that I do not know about.

> I think a new release would help to spread more current versions, as maintainers probably do not want to pack "arbitrary nightly version", because they as "not the developer" never know in which condition the code in an experimental branch/repo is at the point of download.

I've seen maintainers of distros do whatever they want, even going against the advise of the author. So I don't share your thoughts.

> Or do you consider the state of the repo too "unclean" or as not having enought useful updates during the last almost 3 years since the last release?

I have no idea what you trying to state here, where you base this on or are asking with this.

> I noticed you were working a lot on test and rewrite/clean up but some of the commits sounds like they would be pretty useful.

Also no idea what you want to convey with this.

> No request for justification, of course - just curious. 

Hmm, your post though reads as you really want a justification, unclear for what purpose.

**Comment by JustMyGithub** [comment]
wow, that was a quick reply.

It has been a while ago that I had the issue and I don't have the files anymore to reproduce and properly report. Back then I thought it had something to do with old version not supporting compressed splitted e01 images (maybe of specific compression type) but I didn't do more tests, because the "stable" is named 2014XXXX and the experimental did not have the issue I assumed (because of the name scheme) that 2014XXX is just outdated and unmaintained  and only today I noticed that this conclusion was and is wrong.

I am curious why after 3 years (or 6 considering "stable") a request for an experimental release is redirected to the stable version if there are nice improvements you achieved and could share, so I was looking at the commits and trying to conclude what could be the reason - that was why I was writing those sentences.

If you feel that curiosity is a request for justification I am sorry, I just try to understand.

**Comment by joachimmetz** [comment]
> I am curious why after 3 years (or 6 considering "stable") a request for an experimental release is redirected to the stable version if there are nice improvements you achieved and could share,

Because there are also bugs in the experimental version, that don't make it production ready. Work is in progress to add more test coverage. Also realize that this is not the only thing/project that I'm working on, it definitely does not have the highest priority.
