### ISSUE TITLE
How do I create a Linux libewf.so?

### ISSUE THREAD

**Issue by tedsmith** [libyal/libewf#152]
Dear @joachimmetz 

Having largely conquered the Windows side and adding the super library to my utility in the form of DLLs, I now want to do the same for Linux, and possibly OSX. 

I've done this before, also back in 2015, but I want to have new and up-to-date SO files. 

I've used the standard .configure command in Linux Mint 

./configure
make

followed by :

sudo ldconfig

and I got a libewf.so file in .libewf/.libs as usual. 

But, it seems simply copying it to the project folder and setting the filename in the programming project is not the way to do it? Or if it is, something has gone wrong elsewhere because again, I can't seem to load the library with my program, having copied it to my project folder and calling it 'libewf-x64.so'. I'm guessing it's something to do with a Linux dependancy. 

I was thinking that instead of shipping an SO file, I'd instead ask or direct the user to installing the [library package ](https://launchpad.net/ubuntu/+source/libewf) like this one in the Ubuntu package list. But, if the user does do that, what paths and filenames would I use to direct my program to them, without me calling them as seperate external programs? In other words, does a libewf.so or equivalent file get copied to somewhere fairly normal? If so , where? 

Any tips here?

**Comment by joachimmetz** [comment]
> But, it seems simply copying it to the project folder and setting the filename in the programming project is not the way to do it? 

Correct, this is **not** the typically Linux way

> I can't seem to load the library with my program

This is because so the library is in a location `ldconfig` does not know about
If you run `./configure --prefix /usr && make sudo make install` it should install the library in the system library path

> I was thinking that instead of shipping an SO file, I'd instead ask or direct the user to installing the library package like this one in the Ubuntu package list. 

That is the standard approach for most Linux distributions
know that I have no influence over the Ubuntu package name or version and it looks Ubuntu has not been keeping up to date

> But, if the user does do that, what paths and filenames would I use to direct my program to them,

Why do you need the paths? Typically on LInux you would use pkg-config or `-lewf` to link against them.
If I recall `dpkg --listfiles libewf2` (or equiv) should show the path where the library is installed

If you create a deb file you can just indicate it is dependent on libewf2 and `apt-get` (or equiv) will install it automatically as a dependency

**Comment by tedsmith** [comment]
hI @joachimmetz 

I seem to have resolved this is a non-standard but fairly cheeky way. I didn't realise that the LoadLibrary function in my programming launguage requires, on Linux, the FULL path (where as on Windows it checks the project root) to the SO library. 

So this has resolved it : 

libFileName:=ExtractFilePath(Application.ExeName)+'libewf-Linux-x64.so';   

:-) 

So although shipping the SO file with the binary is probably not ideal, it will do for now to help me progress. Thanks
