### ISSUE TITLE
How could i use the libewf in my application in c programing (Ubuntu OS)

### ISSUE THREAD

**Issue by ReninRoy** [libyal/libewf#179]
I want to use the functions in this libewf.so library in my application and need to generate E01 encase file. Please tell me how to link this .so file with my application and step by step procedure for developing the application. Thanks in advance.

**Comment by joachimmetz** [comment]
Have a look at https://github.com/libyal/libewf/wiki/C-development and https://github.com/libyal/libewf/wiki/Building

**Comment by joachimmetz** [comment]
If that is not sufficient, you'll need to ask more specific questions.

**Comment by ReninRoy** [comment]
I am trying to develop a C program for reading ,compressing hard disk data in E01 format and need to write it in a folder of another hard disk. So i am planing to use libewf library. Can you please tell me what all are the APIs need to use and how i can compile the c code in ubuntu os.

**Comment by joachimmetz** [comment]
The 2 links I sent you should get you started, assuming you know the basics of developing C for Ubuntu. Otherwise the ewftools to exactly that what you describe so have a look at that. As I said, unless you have very specific follow up questions, your questions are too generic for me to give you a specific answer.
