### ISSUE TITLE
Struggling assigning NONE, FAST or BEST with libewf_set_compression_values

### ISSUE THREAD

**Issue by tedsmith** [libyal/libewf#33]
Hi Joachim

I'm having some difficulty applying compression. I am using libewf_set_compression_values to assign BEST, LOW, NONE compression to E01 image files (though I notice there's a 'libewf_handle_set_compression_values - perhaps I need to use that?) https://github.com/libyal/libewf/blob/9f678389d18b46db96c6a3b169a46afc2516bf39/libewf/libewf_metadata.c#L732 

I am also assigning LIBEWF_COMPRESSION_LEVELS within my function. (https://github.com/libyal/libewf/blob/9f678389d18b46db96c6a3b169a46afc2516bf39/include/libewf/definitions.h.in)

The user is asked to choose a default, none, fast or best compression method via the GUI and their selection is assigned to an integer var as -1, 0, 1 or 2. 

I then lookup that variables value and, 

if it's -1, libewf_set_compression_values is called with (LIBEWF_COMPRESSION_DEFAULT, 0). 

if it's 0, libewf_set_compression_values is called with (LIBEWF_COMPRESSION_NONE, 0). 

if it's 1, libewf_set_compression_values is called with (LIBEWF_COMPRESSION_FAST, 0). 

if it's 2, libewf_set_compression_values is called with (LIBEWF_COMPRESSION_BEST, 0). 

If the user chooses none, I get an uncompresssed E01 just as expected and hoped. However, if the user chooses FAST or BEST, the resulting image is always the same size. I would expect one to be larger than the other, even if by only a small amount. 

Do I have to call something else? In other words, having SET the compression with libewf_set_compression_values, do I need to call another function to actually incorporate the varying levels of compression?

**Comment by joachimmetz** [comment]
So first of all libewf_set_compression_values is deprecated:
https://github.com/libyal/libewf/blob/master/include/libewf.h.in#L3032

You should use: libewf_handle_set_compression_values since libewf_set_compression_values will be removed sometime in the future
https://github.com/libyal/libewf/blob/master/include/libewf.h.in#L1017

Either way the way you set the compression level is correct.
https://github.com/libyal/libewf/blob/master/include/libewf/definitions.h.in#L109

The value is passed directly to zlib. So the difference between fast or best compression really depends on the input data. libewf offers empty block detection which can detect a 0-byte filled block faster than trying to always compress it, which makes (on average) the overall process of imaging drives faster.

**Comment by tedsmith** [comment]
Thanks a lot for your time as always Joachim. I have incoported the newer call but I think, as you say, I need to look into the empty block detection flags, which I assume are 

LIBEWF_PACK_FLAG_USE_EMPTY_BLOCK_COMPRESSION = $02;

I will close the question because the error is clearly with my implementation somewhere. I just wanted to check I wasn't missing something obvious. That said, if you have the time to look [at my implementation](https://github.com/tedsmith/yaffi/blob/3223fe6cca5a2246647b24aec56fe26f51d4c4a4/UYaffi.pas#L1966), I'd welcome your input.

**Comment by joachimmetz** [comment]
> I will close the question because the error is clearly with my implementation somewhere.

I more leaning towards "working as intended" than "error". As I said the resulting compression ratio will depend on the input data.
