### ISSUE TITLE
Building libewf-experimental-20160403 using MSYS-MinGW on Windows 7 64-bit

### ISSUE THREAD

**Issue by tedsmith** [libyal/libewf#43]
Hi Joachim

I wanted to try using a new DLL compiled from your recent March release. It has been a while since I compiled it last time so it took me a while some reading to do, but having done it, I fear I have done something wrong. 
I followed the instructions [here](https://github.com/libyal/libewf/wiki/Building#using-msys-mingw) to build using Windows 7 64-bit and MSYS-MinGW. Upon completion I had libewf-3.dll and I also went and downloaded libgcc_s_dw2-1.dll from somewhere and copied that to my project folder, along with my existing zlib.dll file and so on. 

Trouble is, my LoadLibraryA call fails. I thought for a while it was due to something I had done, but after a few hours debugging and using Dependancy Walker, I realised that the newly compiled DLL was missing dependancies, namely libbz2-2.dll and zlib1.dll (I have a zlib.dll already, just not zlib1.dll) to start with. But even after downloading those, there remained several other warnings in Dependancy Walker stating that "Error opening file. The system cannot find the file specified" for the following files: 

API-MS-WIN-APPMODEL-RUNTIME-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL
API-MS-WIN-SHCORE-SCALING-L1-1-1.DLL
DCOMP.DLL
IESHIMS.DLL

![untitled](https://cloud.githubusercontent.com/assets/1560598/14713100/af3fed48-07d7-11e6-8a40-3bc624c83f96.png)

So at this stage, I gave up and thought I'd ask you here in case I was missing something obvious. 
Have you compiled the latest libEWF yourself using Windows and MSYS-MinGW? If so, can I ask what else you did to ensure your other projects or any programs can load the resulting libewf.DLL? As it stands, I have the following DLL's in my project folder : 

libbz2-2.dll (downloaded from Internet)
libewf.dll (that I renamed from libewf-3.dll, built with MSYS-MinGW)
libgcc_s_dw2-1.dll (downloaded from Internet)
msvcr100.dll (downloaded from Internet)
zlib.dll (about a year or two old)
zlib1.dll (downloaded from Internet, dated 2013)

Many thanks as always for your time and development work.

**Comment by tedsmith** [comment]
PS...is it not worth thinking about adding a compiled version of the DLL as part of the release, so that developers can just copy it to wherever their programming project is?

**Comment by joachimmetz** [comment]
He Ted,

> I wanted to try using a new DLL compiled from your recent March release.

Still very experimental.

> I followed the instructions here to build using Windows 7 64-bit and MSYS-MinGW.

Those need some updating, I'll do that once I hit alpha stage.

> downloaded libgcc_s_dw2-1.dll from somewhere

This is non-recommended practice for various reasons:

* how far can you trust the downloaded version to be benign?
* possible ABI incompatibilities

The DLL should already be on your system as part of MSYS-MinGW.

> I have a zlib.dll already, just not zlib1.dll

That's because zlib1.dll is the name MSYS-MinGW uses. The DLL should already be on your system as part of MSYS-MinGW.

> The system cannot find the file specified" for the following files:

These dependencies likely get included from one of the other DLLs or maybe the C runtime that MSYS-MinGW links in to libewf DLL.

> Have you compiled the latest libEWF yourself using Windows and MSYS-MinGW?

You'll need to give the github (experimental version some time) I'll look into fixing deployment issues after I fixed all the structural issues in the experimental version.

> PS...is it not worth thinking about adding a compiled version of the DLL as part of the release, so that developers can just copy it to wherever their programming project is?

Yes but this is more tricky then you think e.g. which versions of Windows do you want the DLL to support? Should it rely on Visual Studio C Runtime? If so which version. Am I able to distribute a MSYS-MinGW compiled DLL due to GPL license of some parts of the dependencies?

I also rather use something like [NuGet](https://www.nuget.org/packages) or [Chocolatey](chocolatey.org) to distribute binaries/builds, though these seem more dot.net oriented.

**Comment by tedsmith** [comment]
OK Joachim...that is helpful, thankyou. 

I just wanted to check I wasn't doing something completely wrong which is why I asked. I will wait a while and perhaps you could reply back when\if you make or suggest any changes to the technique. I'm not especially experienced at compiling DLL's and my YAFFI project is the only one where I have the need to so any guidance to the already well documented steps will be welcomed. 

Regarding the other DLL's - I was merely trying to check my compiled libEWF DLL worked, so I just grabbed them from anywhere to run a virtual machine. I realise I would not be advised to distribute them to users....though perhaps a suggested place to get libgcc_s_dw2-1.dll from would be good, as libEWF seems to now require it, as part of your instructions it says so...

**Comment by joachimmetz** [comment]
> though perhaps a suggested place to get libgcc_s_dw2-1.dll from would be good, as libEWF seems to now require it, as part of your instructions it says so...

libgcc_s_dw2-1.dll is part of MinGW, it should be on you build machine, e.g. a Visual Studio built libewf.dll does not have this dependency. If anything in the build system changes, these DLLs can change as well.

**Comment by serius777** [comment]
hi tedsmith, i want to ask to you, how can you compile libewf? i followed same instruction to, but i got error while compiling in libcstring.

> ../libtool: line 1095: lib: command not found
> make[1]: *** [libcstring.la] Error 127
> make: *** [all-recursive] Error 1

do you know this isue?
i using Windows 7 64-bit and MSYS-MinGW.

**Comment by tedsmith** [comment]
Windows 7 64-bit and MSYS-MinGW, just like you, and the instructions that Joachim provided. Are you sure you have everything you need installed?

**Comment by woodruffw** [comment]
> API-MS-WIN-APPMODEL-RUNTIME-L1-1-0.DLL
> API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL
> API-MS-WIN-CORE-WINRT-L1-1-0.DLL
> API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL
> API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL
> API-MS-WIN-SHCORE-SCALING-L1-1-1.DLL
> DCOMP.DLL
> IESHIMS.DLL

I ran across these exact same missing DLLs at load-time when building from master (with VS2015, not MinGW). Those are normally missing when the Visual C++ redestributable isn't installed, but not in this case (I spent quite a few hours tracing down every possible VS VC++ redist package and installing them).

**Comment by serius777** [comment]
Maybe this answer can be late, but i want to share what i did to compile LibEwf library.
I use Msys2 and Mingw64 to build 64 bit library instead of Msys from mingw32.
After installing some dependency (binutils and etc. look [here](https://github.com/libyal/libewf/wiki/Building#using-msys-mingw)) then compile LibEwf with this command
`CPPFLAGS=-DWINVER=0x0501 ./configure --host=x86_64-w64-mingw32`
