### ISSUE TITLE
`dokan.patch` file 404s

### ISSUE THREAD

**Issue by bridgeythegeek** [libyal/libewf#76]
Sadly, I'm trying to build libewf for Windows. In following the [Building guide for Visual Studio](https://github.com/libyal/libewf/wiki/Building#using-microsoft-visual-studio), all was going fine until applying the `dokan.patch`. The [link](https://googledrive.com/host/0B3fBvzttpiiSZDA2Y3hBeWRUUzg/dokan.patch) 404s and my Google Fu wasn't able to drum up a copy from elsewhere.

Is the patch still needed? If so, is it still available somewhere?

(Also, some of the links on the guide are out-of-date. I would've updated the wiki and made a pull request, but the project doesn't allow non-contributors to update the wiki. Happy to do the work if I can!)

**Comment by joachimmetz** [comment]
A patched version of dokan can be found here: https://github.com/joachimmetz/dokan

Know that dokan has been replaced by dokan x and now dokan y (I think).

the wiki is generated automatically by https://github.com/libyal/libyal/blob/master/scripts/wiki-generate.py and temples, feel free to send your PRs there; Otherwise I'll have a look to update and regenerate the wiki as soon as time permits.

**Comment by bridgeythegeek** [comment]
Thank you - your dokan library worked. I shall look to update the wiki and submit a PR.
